-- Consulta à nested table
SELECT o.COD, o.TIPO, o.ORCAMENTO
FROM TB_CLIENTE c, TABLE(c.OBRA) o;

-- Consulta à varray
SELECT c.CNPJ_C,
       c.NOME,
       t.COLUMN_VALUE AS TELEFONE
FROM TB_CLIENTE c,
     TABLE(c.TELEFONE) t;

--Consulta SELECT DEREF
SELECT DEREF(s.ENGENHEIRO).nome AS NOME_ENGENHEIRO, DEREF(s.EQUIPAMENTO).nome AS NOME_EQUIPAMENTO, DEREF(s.FORNECEDOR).nome AS NOME_FORNECEDOR
FROM TB_SOLICITA s;



-- CONSULTA A QUANTIDADE DE IF's PARA CADA SETOR
SELECT SETOR, COUNT(*) AS NUMERO_DE_INSTITUICOES
FROM TB_INSTITUICAO_FINANCEIRA
GROUP BY SETOR;

-- CONSULTA FORNECEDOR
SELECT f.NOME AS NOME_FORNECEDOR,
       f.CNPJ_FORNECEDOR AS CNPJ,
       f.ENDERECO.RUA || ', ' || f.ENDERECO.NUMERO || ', ' || f.ENDERECO.BAIRRO || ', ' || f.ENDERECO.CEP AS ENDERECO_COMPLETO,
       T.COLUMN_VALUE AS TELEFONES,
	   R.COLUMN_VALUE AS RAMOS
FROM TB_FORNECEDOR f, TABLE (F.TELEFONE) T, TABLE(F.RAMO) R