-- DROP TABLE TB_INSTITUICAO_FINANCEIRA;

CREATE TABLE TB_INSTITUICAO_FINANCEIRA OF INSTITUICAO_FINANCEIRA (
    CNPJ_INSTITUICAO PRIMARY KEY
);
/

CREATE TABLE TB_EQUIPAMENTO OF TP_EQUIPAMENTO(
    CODIGO_EQUIPAMENTO PRIMARY KEY
);
/

CREATE TABLE TB_FORNECEDOR OF TP_FORNECEDOR(
    CNPJ_FORNECEDOR PRIMARY KEY
);
/

CREATE TABLE TB_SOLICITA OF TP_SOLICITA(
    data_hora PRIMARY KEY
);
/

-- TABELA CLIENTE
CREATE TABLE TB_CLIENTE OF TP_CLIENTE (
    CNPJ_C PRIMARY KEY
);
/


-- PROJETO
CREATE TABLE TB_PROJETO OF TP_PROJETO (
    CODIGO_PROJETO PRIMARY KEY
);
/
