-- DROP TABLE TB_INSTITUICAO_FINANCEIRA;

CREATE TABLE TB_INSTITUICAO_FINANCEIRA OF INSTITUICAO_FINANCEIRA (
    CNPJ_INSTITUICAO PRIMARY KEY
);
/

CREATE TABLE EQUIPAMENTO OF TP_EQUIPAMENTO(
    CODIGO_EQUIPAMENTO PRIMARY KEY
);
/

CREATE TABLE TB_FORNECEDOR OF TP_FORNECEDOR(
    CNPJ_FORNECEDOR PRIMARY KEY
);
/
