-- DROPS
DROP TABLE INSTITUICAO_FINANCEIRA;
DROP TABLE CLIENTE;
DROP TABLE TELEFONE_CLIENTE;
DROP TABLE OBRA;
DROP TABLE FUNCIONARIO;
DROP TABLE TELEFONE_FUNCIONARIO;
DROP TABLE ENDERECO;
DROP TABLE ENGENHEIRO;
DROP TABLE ESPECIALIZACAO;
DROP TABLE PEDREIRO;
DROP TABLE CAPACITACAO;
DROP TABLE FORNECEDOR;
DROP TABLE TELEFONE_FORNECEDOR;
DROP TABLE EQUIPAMENTO;
DROP TABLE FABRICANTE;
DROP TABLE CONTRATA;
DROP TABLE PROJETO;
DROP TABLE REALIZA;
DROP TABLE SOLICITA;
DROP TABLE RAMO_FORNECEDOR;

-- CRIANDO AS TABELAS SQL
CREATE TABLE INSTITUICAO_FINANCEIRA(
    CNPJ_INSTITUICAO NUMBER,
    NOME VARCHAR2(40) NOT NULL,
    SETOR VARCHAR2(8) NOT NULL CHECK (SETOR IN ('PUBLICO', 'PRIVADO')),
    CONSTRAINT INSTITUICAO_PK PRIMARY KEY (CNPJ_INSTITUICAO)
);

CREATE TABLE CLIENTE(
    CNPJ_CLIENTE NUMBER,
    NOME VARCHAR2(40) NOT NULL,
    RESPONSAVEL VARCHAR2(40),
    CONSTRAINT CLIENTE_PK PRIMARY KEY (CNPJ_CLIENTE)
);

CREATE TABLE TELEFONE_CLIENTE(
    CNPJ_CLIENTE NUMBER,
    TELEFONE_CLIENTE VARCHAR2(11),
    CONSTRAINT TELEFONE_CLIENTE_PK PRIMARY KEY (CNPJ_CLIENTE, TELEFONE_CLIENTE),
    CONSTRAINT CNPJ_CLIENTE_FK FOREIGN KEY (CNPJ_CLIENTE) REFERENCES CLIENTE (CNPJ_CLIENTE)
);

CREATE TABLE OBRA (
    CODIGO_OBRA NUMBER,
    CNPJ_CLIENTE NUMBER,
    DATA_INICIO DATE NOT NULL,
    DATA_ENTREGA DATE,
    TIPO VARCHAR2(40) NOT NULL,
    ORCAMENTO NUMBER NOT NULL,
    CEP VARCHAR2(8),
    NUMERO_ENDERECO NUMBER,
    CONSTRAINT OBRA_PK PRIMARY KEY (CODIGO_OBRA, CNPJ_CLIENTE),
    CONSTRAINT CNPJ_CLIENTE1_FK FOREIGN KEY (CNPJ_CLIENTE) REFERENCES CLIENTE (CNPJ_CLIENTE),
    CONSTRAINT CEP_OBRA_FK FOREIGN KEY (CEP) REFERENCES ENDERECO (CEP)
);

CREATE TABLE ENDERECO (
	CEP VARCHAR2(8),
    BAIRRO VARCHAR2(40) NOT NULL,
    RUA VARCHAR2(255) NOT NULL,
    CONSTRAINT ENDERECO_PK PRIMARY KEY (CEP)
);

CREATE TABLE FUNCIONARIO (
    CPF_FUNCIONARIO NUMBER,
    NOME VARCHAR2(40) NOT NULL,
    SEXO VARCHAR2(1) CHECK (SEXO IN ('M', 'F')),
    SALARIO NUMBER,
    DATA_ADMISSAO DATE NOT NULL,
    CEP VARCHAR2(8) NOT NULL,
    NUMERO_ENDERECO NUMBER,
    CONSTRAINT FUNCIONARIO_PK PRIMARY KEY (CPF_FUNCIONARIO),
    CONSTRAINT CEP_FK FOREIGN KEY (CEP) REFERENCES ENDERECO (CEP)
);

CREATE TABLE TELEFONE_FUNCIONARIO (
    CPF_FUNCIONARIO NUMBER,
    TELEFONE_FUNCIONARIO VARCHAR2(11),
    CONSTRAINT TELEFONE_FUNCIONARIO_PK PRIMARY KEY (CPF_FUNCIONARIO, TELEFONE_FUNCIONARIO),
    CONSTRAINT CPF_FUNCIONARIO_FK FOREIGN KEY (CPF_FUNCIONARIO) REFERENCES FUNCIONARIO (CPF_FUNCIONARIO)
);

CREATE TABLE ENGENHEIRO (
    CPF_ENGENHEIRO NUMBER,
    CARGO VARCHAR2(40) NOT NULL,
    CPF_SUPERVISOR NUMBER,
    CONSTRAINT ENGENHEIRO_PK PRIMARY KEY (CPF_ENGENHEIRO),
    CONSTRAINT CPF_ENGENHEIRO_FK FOREIGN KEY (CPF_ENGENHEIRO) REFERENCES FUNCIONARIO (CPF_FUNCIONARIO),
    CONSTRAINT CPF_SUPERVISOR_FK FOREIGN KEY (CPF_SUPERVISOR) REFERENCES ENGENHEIRO (CPF_ENGENHEIRO)
);

CREATE TABLE ESPECIALIZACAO (
    CPF_ENGENHEIRO NUMBER,
    ESPECIALIZACAO VARCHAR2(40),
    CONSTRAINT ESPECIALIZACAO_ENGENHEIRO_PK PRIMARY KEY (CPF_ENGENHEIRO, ESPECIALIZACAO),
    CONSTRAINT CPF_ENGENHEIRO1_FK FOREIGN KEY (CPF_ENGENHEIRO) REFERENCES ENGENHEIRO (CPF_ENGENHEIRO)
);

CREATE TABLE PEDREIRO (
    CPF_PEDREIRO NUMBER,
    CONSTRAINT PEDREIRO_PK PRIMARY KEY (CPF_PEDREIRO),
    CONSTRAINT CPF_PEDREIRO_FK FOREIGN KEY (CPF_PEDREIRO) REFERENCES FUNCIONARIO (CPF_FUNCIONARIO)
);

CREATE TABLE CAPACITACAO (
    CPF_PEDREIRO NUMBER,
    CAPACITACAO VARCHAR2(40),
    CONSTRAINT CAPACITACAO_PEDREIRO_PK PRIMARY KEY (CPF_PEDREIRO, CAPACITACAO),
    CONSTRAINT CPF_PEDREIRO1_FK FOREIGN KEY (CPF_PEDREIRO) REFERENCES PEDREIRO (CPF_PEDREIRO)
);

CREATE TABLE FORNECEDOR (
    CNPJ_FORNECEDOR NUMBER,
    NOME VARCHAR2(40) NOT NULL,
    CEP VARCHAR2(8) NOT NULL,
    NUMERO_ENDERECO NUMBER,
    CONSTRAINT FORNECEDOR_PK PRIMARY KEY (CNPJ_FORNECEDOR),
    CONSTRAINT CEP1_FK FOREIGN KEY (CEP) REFERENCES ENDERECO (CEP)
);

CREATE TABLE TELEFONE_FORNECEDOR(
    CNPJ_FORNECEDOR NUMBER,
    TELEFONE_FORNECEDOR VARCHAR2(11),
    CONSTRAINT TELEFONE_FORNECEDOR_PK PRIMARY KEY (CNPJ_FORNECEDOR, TELEFONE_FORNECEDOR),
    CONSTRAINT CNPJ_FORNECEDOR_FK FOREIGN KEY (CNPJ_FORNECEDOR) REFERENCES FORNECEDOR (CNPJ_FORNECEDOR)
);

CREATE TABLE EQUIPAMENTO (
    CODIGO_EQUIPAMENTO NUMBER,
    NOME VARCHAR2(40) NOT NULL,
    TIPO VARCHAR2(40) NOT NULL,
    CONSTRAINT EQUIPAMENTO_PK PRIMARY KEY (CODIGO_EQUIPAMENTO)
);

CREATE TABLE FABRICANTE (
    CODIGO_EQUIPAMENTO NUMBER,
    NOME_FABRICANTE VARCHAR2(40) NOT NULL,
    CONSTRAINT FABRICANTE_PK PRIMARY KEY (CODIGO_EQUIPAMENTO),
    CONSTRAINT CODIGO_EQUIPAMENTO_FK FOREIGN KEY (CODIGO_EQUIPAMENTO) REFERENCES EQUIPAMENTO (CODIGO_EQUIPAMENTO)
);

CREATE TABLE PROJETO (
    CPF_ENGENHEIRO NUMBER,
    CODIGO_OBRA NUMBER,
    CNPJ_CLIENTE NUMBER,
    CNPJ_INSTITUICAO NUMBER,
    CONSTRAINT PROJETO_PK PRIMARY KEY (CPF_ENGENHEIRO, CODIGO_OBRA, CNPJ_CLIENTE),
    CONSTRAINT ENGENHEIRO_FK FOREIGN KEY (CPF_ENGENHEIRO) REFERENCES ENGENHEIRO (CPF_ENGENHEIRO),
    CONSTRAINT OBRA_FK FOREIGN KEY (CODIGO_OBRA, CNPJ_CLIENTE) REFERENCES OBRA (CODIGO_OBRA, CNPJ_CLIENTE),
    CONSTRAINT INSTITUICAO_FK FOREIGN KEY (CNPJ_INSTITUICAO) REFERENCES INSTITUICAO_FINANCEIRA (CNPJ_INSTITUICAO)
);


CREATE TABLE REALIZA (
    CPF_PEDREIRO NUMBER,
    CODIGO_OBRA NUMBER,
    CNPJ_CLIENTE NUMBER,
    CONSTRAINT REALIZA_PK PRIMARY KEY (CPF_PEDREIRO, CODIGO_OBRA, CNPJ_CLIENTE),
    CONSTRAINT PEDREIRO1_FK FOREIGN KEY (CPF_PEDREIRO) REFERENCES PEDREIRO (CPF_PEDREIRO),
    CONSTRAINT OBRA1_FK FOREIGN KEY (CODIGO_OBRA, CNPJ_CLIENTE) REFERENCES OBRA (CODIGO_OBRA, CNPJ_CLIENTE)
);

CREATE TABLE SOLICITA (
    CNPJ_FORNECEDOR NUMBER,
    CODIGO_EQUIPAMENTO NUMBER,
    CPF_ENGENHEIRO NUMBER,
    DATA_HORA TIMESTAMP,
    CONSTRAINT SOLICITA_PK PRIMARY KEY (CNPJ_FORNECEDOR, CODIGO_EQUIPAMENTO, CPF_ENGENHEIRO, DATA_HORA),
    CONSTRAINT FORNECEDOR2_FK FOREIGN KEY (CNPJ_FORNECEDOR) REFERENCES FORNECEDOR (CNPJ_FORNECEDOR),
    CONSTRAINT EQUIPAMENTO2_FK FOREIGN KEY (CODIGO_EQUIPAMENTO) REFERENCES EQUIPAMENTO (CODIGO_EQUIPAMENTO),
    CONSTRAINT ENGENHEIRO2_FK FOREIGN KEY (CPF_ENGENHEIRO) REFERENCES ENGENHEIRO (CPF_ENGENHEIRO)
);

CREATE TABLE RAMO_FORNECEDOR (
    CNPJ_FORNECEDOR NUMBER,
    RAMO VARCHAR2(40),
    CONSTRAINT RAMO_PK PRIMARY KEY (CNPJ_FORNECEDOR, RAMO),
    CONSTRAINT FORNECEDOR3_FK FOREIGN KEY (CNPJ_FORNECEDOR) REFERENCES FORNECEDOR (CNPJ_FORNECEDOR)
);